import "~/styles/globals.css";

import type { Metadata } from "next";
import { Geist } from "next/font/google";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html className={`${geist.variable}`} lang="en">
      <body className="max-w-7xl mx-auto">
        <nav className="flex justify-between items-center p-4">
          <Link href="/" className="text-2xl font-bold">
            TS Gallery
          </Link>
          <div className="flex gap-4">
            <Link
              href="/sign-in"
              className="text-md hover:font-semibold text-gray-300 hover:text-white"
            >
              Sign In
            </Link>
          </div>
        </nav>
        {children}
        <footer className="text-center text-sm text-gray-500 p-4">
          <p>&copy; {new Date().getFullYear()} TS Gallery</p>
        </footer>
      </body>
    </html>
  );
}
